#define VPVM_VERSION_MAJOR 0
#define VPVM_VERSION_COMPAT 30
#define VPVM_VERSION_MINOR 0
#define VPVM_VERSION_STRING "0.30.0"
#define VPVM_APPLICATION_NAME "MMDAI2"
#define VPVM_ORGANIZATION_NAME "MMDAI"
#define VPVM_ORGANIZATION_DOMAIN "mmdai.github.com"

